In [1]:
from __future__ import unicode_literals, print_function, division
from io import open
import glob
import os

In [2]:
import torch

In [3]:
import torch.nn as nn

In [59]:
def findFiles(path): return glob.glob(path)
print(findFiles('words/*.xls'))

['words\\english-word-list-total.xls', 'words\\french-word-list-total.xls', 'words\\german-word-list-total.xls', 'words\\italian-word-list-total.xls', 'words\\russian-word-list-total.xls', 'words\\spanish-word-list-total.xls']


In [60]:
import pandas as pd
from pandas import ExcelWriter

In [94]:
df = []
df.append(pd.read_excel('words/english-word-list-total.xls'))
df.append(pd.read_excel('words/french-word-list-total.xls'))
df.append(pd.read_excel('words/german-word-list-total.xls'))
df.append(pd.read_excel('words/italian-word-list-total.xls'))
#df.append(pd.read_excel('words/russian-word-list-total.xls'))
df.append(pd.read_excel('words/spanish-word-list-total.xls'))

In [96]:
print(df[4].iloc[2,0])

de


In [97]:
for i in range(5):
    df[i] = df[i].iloc[2:,]

print(df[1].head(4))
#df = df.iloc[2:,]

    language:     French  Unnamed: 2
1.0        de  484735124    1.000000
2.0        la  260760851    0.537945
3.0        et  224298880    0.462725
4.0        le  213270164    0.439973


In [98]:
'''
en = df[0].iloc[:,0]
fr = df[1].iloc[:,0]
ge = df[2].iloc[:,0]
'''
for i in range(5):
    df[i] = df[i].iloc[:,0]
    df[i] = df[i].iloc[:500]

In [99]:
print(df[4])


1.0                de
2.0                la
3.0               que
4.0                el
5.0                 y
6.0                en
7.0                 a
8.0               los
9.0               del
10.0               se
11.0              las
12.0              por
13.0               un
14.0              con
15.0             para
16.0               no
17.0              una
18.0               es
19.0               su
20.0               al
21.0               lo
22.0             como
23.0              más
24.0                o
25.0             este
26.0             pero
27.0              sus
28.0             esta
29.0               si
30.0               ha
             ...     
471.0        análisis
472.0            mano
473.0         humanos
474.0       instituto
475.0        superior
476.0          propio
477.0           señor
478.0           santa
479.0           favor
480.0       municipio
481.0           cerca
482.0          tierra
483.0       políticas
484.0       programas
485.0     

In [100]:
import unicodedata
import string



In [101]:
def unicodeToAscii(s):
    return ''.join(
        c for c in unicodedata.normalize('NFD', s)
        if unicodedata.category(c) != 'Mn'
        and c in all_letters
    )

all_letters = string.ascii_letters + " .,;'"

In [102]:
print(unicodeToAscii(df[4].get(2)))
print(unicodeToAscii("üüÖÖééäà"))


la
uuOOeeaa


In [103]:
# taken from the pytorch tutorial
n_letters = len(all_letters)

# Find letter index from all_letters, e.g. "a" = 0
def letterToIndex(letter):
    return all_letters.find(letter)

# Just for demonstration, turn a letter into a <1 x n_letters> Tensor
def letterToTensor(letter):
    tensor = torch.zeros(1, n_letters)
    tensor[0][letterToIndex(letter)] = 1
    return tensor

# Turn a line into a <line_length x 1 x n_letters>,
# or an array of one-hot letter vectors
def lineToTensor(line):
    tensor = torch.zeros(len(line), 1, n_letters)
    for li, letter in enumerate(line):
        tensor[li][0][letterToIndex(letter)] = 1
    return tensor

In [104]:
print(lineToTensor(df[3].get(25)))

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 1.]]])


In [105]:
df[2]

1.0                 die
2.0                 und
3.0                 der
4.0                  in
5.0                 das
6.0                 den
7.0                  zu
8.0                 mit
9.0                 ist
10.0                von
11.0                für
12.0                auf
13.0              nicht
14.0                 es
15.0                ein
16.0                 im
17.0               auch
18.0               sich
19.0                ich
20.0                sie
21.0               eine
22.0                dem
23.0                des
24.0                 an
25.0                als
26.0             werden
27.0                bei
28.0               sind
29.0               dass
30.0                 so
              ...      
471.0             Abend
472.0           mehrere
473.0            damals
474.0             Preis
475.0            lernen
476.0    beispielsweise
477.0         einzelnen
478.0            Gruppe
479.0         weiterhin
480.0             deine
481.0           

In [109]:
en = []
fr = []
ge = []
it = []
sp = []
category_dict = {0: en, 1: fr, 2: ge, 3: it, 4: sp}

def toCategory(num):
    if (num == 0):
        return 'english'
    elif (num == 1):
        return 'french'
    elif (num == 2):
        return 'german'
    elif (num == 3):
        return 'italian'
    elif (num == 4):
        return 'spanish'
    else:
        return 'category not handled'


In [114]:
for i in range(5):
    for j in range(500):
        category_dict[i].append(unicodeToAscii(df[i].get(j+1)))

In [123]:
print(category_dict[2][289])

'''
df.append(pd.read_excel('words/english-word-list-total.xls'))
df.append(pd.read_excel('words/french-word-list-total.xls'))
df.append(pd.read_excel('words/german-word-list-total.xls'))
df.append(pd.read_excel('words/italian-word-list-total.xls'))
#df.append(pd.read_excel('words/russian-word-list-total.xls'))
df.append(pd.read_excel('words/spanish-word-list-total.xls'))
'''

erhalten


"\ndf.append(pd.read_excel('words/english-word-list-total.xls'))\ndf.append(pd.read_excel('words/french-word-list-total.xls'))\ndf.append(pd.read_excel('words/german-word-list-total.xls'))\ndf.append(pd.read_excel('words/italian-word-list-total.xls'))\n#df.append(pd.read_excel('words/russian-word-list-total.xls'))\ndf.append(pd.read_excel('words/spanish-word-list-total.xls'))\n"

In [124]:
n_categories = 5

class RNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(RNN, self).__init__()

        self.hidden_size = hidden_size

        self.i2h = nn.Linear(input_size + hidden_size, hidden_size)
        self.i2o = nn.Linear(input_size + hidden_size, output_size)
        self.softmax = nn.LogSoftmax(dim=1)

    def forward(self, input, hidden):
        combined = torch.cat((input, hidden), 1)
        hidden = self.i2h(combined)
        output = self.i2o(combined)
        output = self.softmax(output)
        return output, hidden

    def initHidden(self):
        return torch.zeros(1, self.hidden_size)

n_hidden = 138
rnn = RNN(n_letters, n_hidden, n_categories)

In [187]:
hidden = torch.zeros(1, n_hidden)

for line in lineToTensor('und'):
    print(line)
    print(hidden)
    out, hid = rnn(line, hidden)
    hidden = hid
print(out)
print(hid)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [153]:
category_dict[0].insert(0, 'english')
len(category_dict[0])


1003

In [156]:
category_dict[0] = category_dict[0][:500]
category_dict[0]

['english',
 'english',
 'the',
 'and',
 'to',
 'of',
 'a',
 'in',
 'is',
 'that',
 'for',
 'I',
 'you',
 'it',
 'with',
 'on',
 'as',
 'are',
 'be',
 'this',
 'was',
 'have',
 'or',
 'at',
 'not',
 'your',
 'from',
 'we',
 'by',
 'will',
 'can',
 'but',
 'they',
 'an',
 'he',
 'all',
 'has',
 'if',
 'their',
 'one',
 'do',
 'more',
 "n't",
 'my',
 'his',
 'so',
 'there',
 'about',
 'which',
 'when',
 'what',
 'out',
 'up',
 'our',
 'who',
 'also',
 'had',
 'time',
 'some',
 'would',
 'were',
 'like',
 'been',
 'just',
 'her',
 'new',
 'other',
 'them',
 'she',
 'people',
 'these',
 'no',
 'get',
 'how',
 'me',
 'into',
 'than',
 'only',
 'its',
 'most',
 'may',
 'any',
 'many',
 'make',
 'then',
 'well',
 'first',
 'very',
 'over',
 'now',
 'could',
 'after',
 'even',
 'because',
 'us',
 'said',
 'good',
 'way',
 'two',
 'should',
 'work',
 'use',
 'through',
 'see',
 'know',
 'did',
 'much',
 'where',
 'years',
 'need',
 'him',
 'back',
 'such',
 'those',
 'being',
 'day',
 'take',
 

In [159]:
category_dict[0].pop(0)
category_dict[0].append('needed')
print(category_dict[0][498])

needed


In [163]:
category_dict[0].insert(0, 'english')
category_dict[0][0]
len(category_dict[0])

500

In [164]:
category_dict[1].insert(0, 'francais')
category_dict[2].insert(0, 'deutsch')
category_dict[3].insert(0, 'italiano')
category_dict[4].insert(0, 'espanol')

In [165]:
for i in range(5):
    category_dict[i] = category_dict[i][:500]
    assert len(category_dict[i]) == 500

In [176]:
def toIndex(df):
    if df == 'english':
        return 0
    elif df == 'francais':
        return 1
    elif df == 'deutsch':
        return 2
    elif df == 'italiano':
        return 3
    elif df == 'espanol':
        return 4
    else:
        return 0

for i in range(5):
    for j in range(500):
        category_dict[i][j] = category_dict[i][j].lower()

In [177]:
import random

def randomChoice(l):
    return l[random.randint(0, len(l) - 1)]
    # return r, l[r]

def randomTrainingExample():
    df = randomChoice(category_dict)
    line = randomChoice(df)
    category_nr = toIndex(df[0])
    category_tensor = torch.tensor([category_nr], dtype=torch.long)
    line_tensor = lineToTensor(line)
    return category_nr, line, category_tensor, line_tensor

for i in range(10):
    category, line, category_tensor, line_tensor = randomTrainingExample()
    print('category =', category, '/ line =', line, '/ category tensor =', category_tensor, '/ line tensor=', line_tensor)

category = 4 / line = por / category tensor = tensor([4]) / line tensor= tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0.]]])
category = 1 / line = seront / category tensor = tensor([1]) / line tensor= tensor([[[0., 0., 0., 0., 0., 0., 0., 

In [178]:
criterion = nn.NLLLoss()

In [179]:
learning_rate = 0.007 # If you set this too high, it might explode. If too low, it might not learn

def train(category_tensor, line_tensor):
    hidden = rnn.initHidden()

    rnn.zero_grad()

    for i in range(line_tensor.size()[0]):
        output, hidden = rnn(line_tensor[i], hidden)

    loss = criterion(output, category_tensor)
    loss.backward()

    # Add parameters' gradients to their values, multiplied by learning rate
    for p in rnn.parameters():
        p.data.add_(-learning_rate, p.grad.data)

    return output, loss.item()

In [181]:
def categoryFromOutput(output):
    top_n, top_i = output.topk(1)
    category_i = top_i[0].item()
    return toCategory(category_i), category_i

print(categoryFromOutput(out))

('french', 1)


In [ ]:
import time
import math

n_iters = 100000
print_every = 5000
#plot_every = 1000

current_loss = 0
all_losses = []

def timeSince(since):
    now = time.time()
    s = now - since
    m = math.floor(s / 60)
    s -= m * 60
    return '%dm %ds' % (m, s)

start = time.time()

for iter in range(1, n_iters + 1):
    category, line, category_tensor, line_tensor = randomTrainingExample()
    output, loss = train(category_tensor, line_tensor)
    current_loss += loss

    # Print iter number, loss, name and guess
    if iter % print_every == 0:
        guess, guess_i = categoryFromOutput(output)
        correct = '✓' if guess_i == category else '✗ (%s)' % category
        print('%d %d%% (%s) %.4f %s / %s %s' % (iter, iter / n_iters * 100, timeSince(start), loss, line, guess, correct))
        print(current_loss/print_every)
        current_loss = 0

    #Add current loss avg to list of losses
    #if iter % plot_every == 0:
    #    all_losses.append(current_loss / plot_every)
    #    current_loss = 0